### ISSUE TITLE
Sovs?

### ISSUE THREAD

**Issue by LFalch** [WonkyGang/discussion-board#1]
@try100try

**Comment by try100try** [comment]
Prøv at deranke dit repo til at være mindre end bare **DUMMY THICC**.

**Comment by LFalch** [comment]
Jeg taler kun dansk

**Comment by try100try** [comment]
Jeg er desværre fra Italien, og da mit engelsk ikke er super godt kan jeg desværre ikke hjælpe dig med dit nuværende problem omkring sovs i dit D U M M Y T H I C C projekt.
-Mvh: megataber

**Comment by LFalch** [comment]
Jeg tror du misforstår. Dette er intet projekt. Dette er bare et spørgsmål om sovs. Måske kan vi endda bedre forstå det uendelige spørgsmål: sovs eller sauce? Ja, man har vel lov at håbe, men meget kan vi nok ikke regne med.

**Comment by try100try** [comment]
Ja, men da jeg er fra det sjældne land også kendt som Letland, har jeg et kæmpe problem med at forstå dette ord "sovs" eller "sauce" da i mit hjemland har vi aldrig rigtigt haft ordentlig føde, dog har jeg en mindre populær mening og jeg vil personligt selv kalde det: souvse.
-Mvh: hypertaber
